name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your default branch if it's not 'main'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Config Secrets File
        env:
          SB_URL: ${{ secrets.SUPABASE_URL }}
          SB_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          echo "const SUPABASE_URL_SECRET = '${SB_URL}';" > config-secrets.js
          echo "const SUPABASE_ANON_KEY_SECRET = '${SB_KEY}';" >> config-secrets.js
          echo "config-secrets.js created for deployment."

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
